# Generated by Django 4.0.5 on 2022-07-20 16:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('content', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('date_modified', models.DateTimeField(default=datetime.datetime.now)),
                ('impressions', models.IntegerField(default=0)),
                ('draft', models.BooleanField(default=True)),
                ('blocked', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blogs.blog')),
            ],
        ),
    ]
